on:
  push:
    branches:
      - main
      - master

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.2.4
        with:
          token: {{ secrets.RENOVATEBOT_TOKEN }}
